#v1 for compatability with Circle CI
emblem-web-server:
  build: .
  ports:
   - "3000:3000"
  volumes:
   - .:/usr/emblem-web
  environment:
   - DBHOST=emblem-db
  links:
   - emblem-db
  command: npm start
emblem-db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=emblem
