#v1 for compatability with Circle CI
emblem-web-server:
  build: .
  ports:
   - "3000:3000"
  volumes:
   - .:/usr/emblem-web
  environment:
   - DBHOST=emblem-db
   - SESSION_SECRET=${SESSION_SECRET}
   - FACEBOOK_ID=${FACEBOOK_ID}
   - FACEBOOK_SECRET=${FACEBOOK_SECRET}
   - AWS_ID=${AWS_ID}
   - AWS_SECRET=${AWS_SECRET}
  links:
   - emblem-db
  command: npm start
emblem-db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=emblem
  ports:
    - "5432:5432"
